stages:
    - release
    - build

######################
## Continous Builds ##
######################

.continous-job-base:
    tags:
        - catalina
        - amd64
    stage: build
    only:
        - merge_requests
    interruptible: true

.continous-build-ios:
    script:
        - ./buildVLCMediaLibraryKit.sh -b -l -v

.continous-build-tvos:
    script:
        - ./buildVLCMediaLibraryKit.sh -b -l -v -t

continous-VLCMediaLibraryKit-iOS:
    extends:
        - .continous-job-base
        - .continous-build-ios

continous-VLCMediaLibraryKit-tvOS:
    extends:
        - .continous-job-base
        - .continous-build-tvos

####################
## Release builds ##
####################

.release-job-base:
    tags:
        - catalina
    stage: release
    only:
        - tags
    artifacts:
        paths:
            - ./build/*.zip
            - ./build/*.patch

VLCMediaLibraryKit:
    extends: .release-job-base
    script:
        - ./buildVLCMediaLibraryKit.sh -b -l -f
        - ./createDeployable.sh -v ${CI_COMMIT_TAG}
