stages:
    - release
    - build

######################
## Continous Builds ##
######################

.continous-job-base:
    tags:
        - monterey-m1-lasvegas
    stage: build
    only:
        - merge_requests
    interruptible: true

.continous-build-ios:
    script: |
        export PATH="/Users/videolanci/sandbox/bin:$PATH"

        ./buildVLCMediaLibraryKit.sh -l -v

.continous-build-tvos:
    script: |
        export PATH="/Users/videolanci/sandbox/bin:$PATH"

        ./buildVLCMediaLibraryKit.sh -l -v -t

continous-VLCMediaLibraryKit-iOS:
    extends:
        - .continous-job-base
        - .continous-build-ios

continous-VLCMediaLibraryKit-tvOS:
    extends:
        - .continous-job-base
        - .continous-build-tvos

####################
## Release builds ##
####################

.release-job-base:
    tags:
        - monterey-m1-lasvegas
    stage: release
    only:
        - tags
    artifacts:
        paths:
            - ./build/*.zip
            - ./build/*.patch

VLCMediaLibraryKit:
    extends: .release-job-base
    script: |
        export PATH="/Users/videolanci/sandbox/bin:$PATH"

        ./buildVLCMediaLibraryKit.sh -l -f
        ./createDeployable.sh -v ${CI_COMMIT_TAG}
