stages:
    - nightly
    - release

####################
## Nightly builds ##
####################

.nightly-job-base:
   tags:
       - macos
   stage: nightly
   only:
       - schedules
   artifacts:
       paths:
           - ./build/*.zip

nightly-VLCMediaLibraryKit:
    extends: .nightly-job-base
    script:
        - ./buildVLCMediaLibraryKit.sh -vck
        - ./createDeployable.sh -v `date +%Y%m%d-%H%M`

####################
## Release builds ##
####################

.release-job-base:
    tags:
        - macos
    stage: release
    only:
        - tags
    artifacts:
        paths:
            - ./build/*.zip

VLCMediaLibraryKit:
    extends: .release-job-base
    script:
        - ./buildVLCMediaLibraryKit.sh -vck
        - ./createDeployable.sh -v ${CI_COMMIT_TAG}
