stages:
    - release

####################
## Release builds ##
####################

.release-job-base:
    tags:
        - catalina
    stage: release
    only:
        - tags
    artifacts:
        paths:
            - ./build/*.zip

VLCMediaLibraryKit:
    extends: .release-job-base
    script:
        - ./buildVLCMediaLibraryKit.sh -b -t
        - ./createDeployable.sh -v ${CI_COMMIT_TAG}
